// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3vykGZHWBjgekLFVAKWv4QBU1Rqq74ww',
    appId: '1:507254725905:web:96b9c19b2e5781f660c0b0',
    messagingSenderId: '507254725905',
    projectId: 'query-baaee',
    authDomain: 'query-baaee.firebaseapp.com',
    storageBucket: 'query-baaee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ubn4Brfi76t3phZ2n6E-xp6OitnThKY',
    appId: '1:507254725905:android:f56afd54ca4ca90d60c0b0',
    messagingSenderId: '507254725905',
    projectId: 'query-baaee',
    storageBucket: 'query-baaee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDc_UoAiY3fGXT63meusHnkpQQZ_5YzIY',
    appId: '1:507254725905:ios:aa853635ee55492060c0b0',
    messagingSenderId: '507254725905',
    projectId: 'query-baaee',
    storageBucket: 'query-baaee.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDc_UoAiY3fGXT63meusHnkpQQZ_5YzIY',
    appId: '1:507254725905:ios:aa853635ee55492060c0b0',
    messagingSenderId: '507254725905',
    projectId: 'query-baaee',
    storageBucket: 'query-baaee.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3vykGZHWBjgekLFVAKWv4QBU1Rqq74ww',
    appId: '1:507254725905:web:886420da4cb80e6060c0b0',
    messagingSenderId: '507254725905',
    projectId: 'query-baaee',
    authDomain: 'query-baaee.firebaseapp.com',
    storageBucket: 'query-baaee.firebasestorage.app',
  );
}
