name: my_flutter_app
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.4
  graphql_flutter: ^5.1.2
  fluttertoast: ^8.2.10
  flutter_markdown: ^0.6.15
  pinput: ^5.0.1
  flutter_dotenv: ^5.2.1
  encrypt: ^5.0.3
  flutter_math_fork: ^0.7.2
  markdown: ^7.1.1
  flutter_tex: ^4.0.13
  carousel_slider: ^4.2.1
  gpt_markdown: ^1.0.11
  timeago: ^3.7.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.4.3
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/askme-logo.png'
  adaptive_icon_foreground: 'assets/askme-logo-bg.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jwt_decoder: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/.env
